// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    country_revenue_chart: {
        name: "country_revenue_chart";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType DOUBLE */
          total_revenue: number;
          /** @sqlType BIGINT */
          payment_count: number;
        }>;
      };
    country_users_chart: {
        name: "country_users_chart";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType BIGINT */
          user_count: number;
          /** @sqlType BIGINT */
          property_count: number;
          /** @sqlType BIGINT */
          payment_count: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
        }>;
      };
    global_kpis: {
        name: "global_kpis";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          country_count: number;
          /** @sqlType BIGINT */
          total_users: number;
          /** @sqlType BIGINT */
          total_properties: number;
          /** @sqlType BIGINT */
          total_payments: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
          /** @sqlType BIGINT */
          host_count: number;
          /** @sqlType BIGINT */
          paying_user_count: number;
        }>;
      };
    host_countries_chart: {
        name: "host_countries_chart";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType BIGINT */
          host_count: number;
          /** @sqlType BIGINT */
          total_properties: number;
          /** @sqlType DOUBLE */
          avg_base_price: number;
        }>;
      };
    host_property_summary: {
        name: "host_property_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          user_id: number;
          /** @sqlType STRING */
          host_name: string;
          /** @sqlType STRING */
          host_country: string;
          /** @sqlType BOOLEAN */
          is_business: boolean;
          /** @sqlType BIGINT */
          property_count: number;
          /** @sqlType DOUBLE */
          avg_base_price: number;
          /** @sqlType DOUBLE */
          total_listing_value: number;
          /** @sqlType DOUBLE */
          avg_max_guests: number;
        }>;
      };
    user_payment_summary: {
        name: "user_payment_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          user_id: number;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          user_type: string;
          /** @sqlType BIGINT */
          completed_payments: number;
          /** @sqlType DOUBLE */
          total_paid: number;
          /** @sqlType DOUBLE */
          avg_payment_amount: number;
          /** @sqlType TIMESTAMP */
          last_payment_date: string;
        }>;
      };
  }
}
